name: Mr.Traen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.21967
title: Reel Mr.Traen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1819'
    - '#a21c28'
    - '#c8858b'
    - '#a1597c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
